id: TwUserLinky
key: TwUserLinky
name: TwUserLinky Plugin
version: 1.2
description: <__trans phrase="Twitter User auto link">
author_name: maRk
author_link: http://labs.markdiary.com/
doc_link: http://labs.markdiary.com/logs/2012/06/twuserlinky-pluguin.html

blog_config_template: config.tmpl
l10n_lexicon:
    ja: l10n_ja.yaml
settings:
    twLinky_seg:
        Default: 'false'
        Scope: blog
    twLinky_target:
        Default: 'false'
        Scope: blog
    twLinky_class:
        Default: 'true'
        Scope: blog
tags:
    modifier:
        TwUserLink: $TwUserLinky::TwUserLinky::Tags::_hdlr_tw_user_link
